version: '3'

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.ch
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - 5050:80
    networks:
      - terminator
    volumes:
      - terminator-pgadmin:/root/.pgadmin
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=terminator
    ports:
      - 5432:5432
    networks:
      - terminator
    volumes:
      - terminator-postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - terminator
    volumes:
      - terminator-redis:/data

networks:
  terminator:
    driver: bridge

volumes:
  terminator-pgadmin:
  terminator-postgres:
  terminator-redis:
